# Commands to start on workspace startup
tasks:
  - name: Setup
    init: >
      yarn; 
      yarn build;
      gp sync-done setup;
    command: echo "Setup done"
  - name: Dev Server
    init: gp sync-await setup
    command: yarn dev

# Ports to expose on workspace startup
ports:
  # Nextjs
  - port: 3000
    onOpen: ignore
    visibility: public 

vscode:
  extensions:
    - dbaeumer.vscode-eslint 
    - esbenp.prettier-vscode
    - eamodio.gitlens
    - pflannery.vscode-versionlens
    - wix.vscode-import-cost 
    - bradlc.vscode-tailwindcss
    - bierner.markdown-preview-github-styles
    - pkief.material-icon-theme
